# Generated by Django 4.2.5 on 2023-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_student', models.CharField(max_length=20)),
                ('email_student', models.CharField(max_length=50)),
                ('entrypassword', models.CharField(max_length=20)),
                ('repeat_entrypassword', models.CharField(max_length=20)),
                ('original_features', models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
